add_subdirectory(gdal)
add_subdirectory(gisFiles)
add_subdirectory(vectorLayer)
set(IOLib fishnet_io)
add_library(${IOLib} INTERFACE)
target_include_directories(${IOLib} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(${IOLib} INTERFACE io_gis io_gdal_adapter io_vector )
add_library(${FISHNET}::IO ALIAS ${IOLib})