//
// Created by grube on 23.09.2021.
//

#ifndef BACHELORARBEIT_WSFTYPEENUM_H
#define BACHELORARBEIT_WSFTYPEENUM_H

enum class WSFTypeEnum {
    AREA, POPULATION, IMPERVIOUSNESS, OTHER, NETWORK
};


#endif //BACHELORARBEIT_WSFTYPEENUM_H
