image: logru/fishnet-deps:latest
workflow:
  rules:
    - changes:
        - app/** 
        - lib/** 
        - tests/** 
        - CMakeLists.txt    
    - if: $CI_COMMIT_BRANCH != "main"
      when: never
stages:
  - build
  - test
build:
  stage: build
  tags: [secloud]
  script:
    - mkdir build
    - cd build
    - cmake -DFISHNET_APPS=OFF ..
    - cmake --build . -j 8
  artifacts:
    paths:
      - build/ # Preserving the build artifacts for the test stage
    expire_in: 1 hour
test:
  stage: test
  tags: [secloud]
  dependencies:
    - build
  script:
    - cd build
    - ctest --output-on-failure
