FROM memgraph/memgraph:latest
RUN apt-get update && apt-get install -y \
    libgdal-dev \
    libssl-dev \
    build-essential \
    gcc-13\
    cmake \
    git \
    nodejs \
    npm \
    python3 \
    python3-pip \
    python3-venv && \
    apt-get clean