# include(${CMAKE_SOURCE_DIR}/extern/quadtree.cmake)
set(GeometryAlgoLib fishnet_geometry_algorithm)
add_library(${GeometryAlgoLib} INTERFACE)
# ExternalProject_Get_Property(Quadtree SOURCE_DIR)
# target_include_directories(${GeometryAlgoLib} INTERFACE ${SOURCE_DIR}/include)
target_include_directories(${GeometryAlgoLib} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(${GeometryAlgoLib} INTERFACE ${FISHNET}::Concepts ${FISHNET}::Geometry::Objects)
add_library(${FISHNET}::Geometry::Algorithm ALIAS ${GeometryAlgoLib})
