include(GoogleTest)
add_subdirectory(graph)
add_subdirectory(io)
add_subdirectory(geometry)
add_subdirectory(util)
add_subdirectory(sandbox)
add_subdirectory(math)
if(FISHNET_APPS)
    add_subdirectory(workflow)
endif()
set(TestUtilLib fishnet_testutil)
add_library(${TestUtilLib} INTERFACE)
target_include_directories(${TestUtilLib} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(${TestUtilLib} INTERFACE gtest_main ${FISHNET}::Math)
add_library(Fishnet::Test ALIAS ${TestUtilLib})