if (NOT ${FISHNET_TEST_LIB})
    message(FATAL_ERROR "Fishnet Testutil Library not build. Aborting tests...")
    return()
endif()
include(GoogleTest)
add_subdirectory(clustering)
add_subdirectory(collections)
add_subdirectory(graph)
add_subdirectory(io)
add_subdirectory(geometry)
add_subdirectory(misc)
add_subdirectory(math)
add_subdirectory(workflow)