if (NOT ${FISHNET_TEST_LIB})
    message(WARNING "Fishnet Testutil Library not build. Aborting tests...")
    return()
endif()
include(GoogleTest)
add_subdirectory(clustering)
add_subdirectory(collections)
add_subdirectory(graph)
add_subdirectory(io)
add_subdirectory(geometry)
add_subdirectory(sandbox)
add_subdirectory(math)
if(FISHNET_APPS)
    add_subdirectory(workflow)
endif()