# Build stage
ARG BASE_IMAGE=logru/fishnet-deps:latest
FROM ${BASE_IMAGE} AS build
COPY . /fishnet
RUN mkdir -p /fishnet/build
WORKDIR /fishnet/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DFISHNET_TEST=OFF -DFISHNET_TEST_LIB=OFF -DFISHNET_APPS=ON -DFISHNET_EXAMPLES=OFF .. 
RUN cmake --build . --config Release -j 8
RUN cmake --install .

# Runtime stage
FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.2 AS runtime
COPY --from=build /usr/local/bin /usr/local/bin
COPY --from=build /usr/local/lib /usr/local/lib
