FROM ghcr.io/osgeo/gdal:ubuntu-small-3.12.2
# Install dependencies and build tools
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    && apt-get clean
RUN ln -sf /usr/include /usr/include/gdal
