set(ClusteringLib fishnet_clustering)
add_library(${ClusteringLib} INTERFACE)
target_include_directories(${ClusteringLib} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(${ClusteringLib} INTERFACE ${FISHNET}::Graph ${FISHNET}::Geometry)
add_library(${FISHNET}::Clustering ALIAS ${ClusteringLib})