add_subdirectory(linear)
add_subdirectory(shapes)
add_subdirectory(compound)
add_subdirectory(base)
set(GeometryObjLib fishnet_geometry_objects)
add_library(${GeometryObjLib} INTERFACE)
target_link_libraries(${GeometryObjLib} INTERFACE geometry_linear_features geometry_shape_features geometry_compound_features geometry_objects_base)
add_library(${FISHNET}::Geometry::Objects ALIAS ${GeometryObjLib})