include(${FISHNET_SOURCE_DIR}/extern/json.cmake)
SET(GraphAdjacencyLib fishnet_graph_adjacency)
add_library(${GraphAdjacencyLib} INTERFACE)
target_include_directories(${GraphAdjacencyLib} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(${GraphAdjacencyLib} INTERFACE util nlohmann_json::nlohmann_json)
add_library(${FISHNET}::Graph::Adjacency ALIAS ${GraphAdjacencyLib})