SET(SETTLEMENT_WORKFLOW_LIBRARY ${FISHNET_WORKFLOW_LIBRARY}-settlementWorkflow)
add_library(${SETTLEMENT_WORKFLOW_LIBRARY} INTERFACE)
target_link_libraries(${SETTLEMENT_WORKFLOW_LIBRARY} INTERFACE Fishnet::Fishnet ${FISHNET_WORKFLOW_LIBRARY}-memgraphAdapter)
target_include_directories(${SETTLEMENT_WORKFLOW_LIBRARY} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)