set(GDALAdapterLib fishnet_io_gdal_adapter)
add_library(${GDALAdapterLib} INTERFACE)
find_package(GDAL  REQUIRED)
find_package(GDAL REQUIRED)
if (GDAL_FOUND)
  message(STATUS "Found GDAL: ${GDAL_VERSION}")
  message(STATUS "Using GDAL include dir: ${GDAL_INCLUDE_DIR}")
  message(STATUS "Using GDAL libraries: ${GDAL_LIBRARIES}")
endif()
target_include_directories(${GDALAdapterLib} INTERFACE ${CMAKE_CURRENT_LIST_DIR}/include)
target_link_libraries(${GDALAdapterLib} INTERFACE ${FISHNET}::Geometry::Objects GDAL::GDAL io_vector)
add_library(${FISHNET}::IO::GDAL ALIAS ${GDALAdapterLib})

