name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: logru/fishnet-deps:latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir build -C ${{env.BUILD_TYPE}} --output-on-failure
  docs:
    runs-on: ubuntu-latest
    container:
      image: logru/fishnet-deps:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DFISHNET_DOCS=ON

    - name: Build Doxygen
      run: cmake --build build --target docs

    - name: Deploy to GH Actions
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc/html


